import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>WareHouse Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by visiting&nbsp;
            <code className={styles.code}>https://github.com/abbyshabi</code>
          </p>
          <div>
            <h5> Nothing to see here but </h5>
            <a
              href="/picking-list"
              target="_blank"
              rel="noopener noreferrer"
            >
             View Picking List
            </a>
            <a
              href="/packing-list/all"
              target="_blank"
              rel="noopener noreferrer"
            >
             View Packing List
            </a>
            <a
              href="/packing-list/1"
              target="_blank"
              rel="noopener noreferrer"
            >
             View Order 1
            </a>
            <a
              href="/packing-list/2"
              target="_blank"
              rel="noopener noreferrer"
            >
             View Order 2
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
